version: "3.7"

services:
  api:
    build:
      context: ./back_gov
      
    ports:
      - "3333:3333"


  web:
    build: 
      context: ./front_gov
      args:
        - VITE_URL_HOST_API=http://localhost:3333

    ports:
      - "8080:8080"

    depends_on:
      - api